/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Javier
 */
public class EcuacionView extends javax.swing.JFrame {

    private javax.swing.JTextField jTmatrix[][];
    private javax.swing.JTextField jTmatrixResult[];
    private final int WMATRIXBOX = 30;
    private final int HMATRIXBOX = 30;

    public EcuacionView() {
        initComponents();
        initJTmatrixComponents();
        setLocationRelativeTo(null);
    }

    public void initJTmatrixComponents() {
        initMatrixArray();
        posJTmatrix();
        posJTmatrixResult();
    }

    public void initMatrixArray() {
        jTmatrix = new JTextField[5][5];
        jTmatrixResult = new JTextField[5];
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                jTmatrix[i][j] = new JTextField();
                jTmatrixResult[i] = new JTextField();
            }
        }
    }

    public void posJTmatrix() {
        int matrixAposX;
        int matrixAposY = 140;

        for (int i = 0; i < 5; i++) {
            matrixAposX = 175;
            for (int j = 0; j < 5; j++) {
                jTmatrix[i][j].setHorizontalAlignment(JTextField.CENTER);
                jTmatrix[i][j].setEditable(false);
                jPMatrixPanel.add(jTmatrix[i][j], new org.netbeans.lib.awtextra.AbsoluteConstraints(matrixAposX, matrixAposY, WMATRIXBOX, HMATRIXBOX));
                matrixAposX += 30;
            }
            matrixAposY += 30;
        }
    }

    public void posJTmatrixResult() {
        int matrixRposX;
        int matrixRposY = 320;
        for (int i = 0; i < 5; i++) {
            matrixRposX = 175;
            for (int j = 0; j < 5; j++) {
                jTmatrixResult[i].setEditable(false);
                jTmatrixResult[i].setHorizontalAlignment(JTextField.CENTER);
                jPMatrixPanel.add(jTmatrixResult[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(matrixRposX, matrixRposY, WMATRIXBOX * 2, HMATRIXBOX));
            }
            matrixRposY += 30;
        }
    }

    public void showResult(float[][] resultData) {
        for (int i = 0; i < resultData.length; i++) {
            for (int j = 0; j < resultData[i].length; j++) {
                jTmatrixResult[i].setText(String.format("%.2f", resultData[i][j]));
            }
        }
    }
    
   public void habilitarMatrixA(int row, int column) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if (i >= row || j >= column) {
                    jTmatrix[i][j].setEditable(false);
                    jTmatrix[i][j].setText("");
                } else {
                    jTmatrix[i][j].setEditable(true);
                }
            }
        }
    }

    public void cleabBlankSpaceA(int row, int column) {
        
    }

    public void cleabBlankSpaceB(int row, int column) {

    }

    public void cleabBlankSpaceResult(int row, int column) {

    }

    public JButton getjBCramer() {
        return jBCramer;
    }

    public JButton getjBGauss() {
        return jBGauss;
    }

    public JTextField getjTColumnaA() {
        return jTColumnaA;
    }

    public JTextField getjTFilaA() {
        return jTFilaA;
    }

    public JTextField[][] getjTmatrix() {
        return jTmatrix;
    }

    public JButton getjBSetMatrix() {
        return jBSetMatrix;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMatrixPanel = new javax.swing.JPanel();
        jLTittle = new javax.swing.JLabel();
        jLFILA = new javax.swing.JLabel();
        jTFilaA = new javax.swing.JTextField();
        jLCOL = new javax.swing.JLabel();
        jTColumnaA = new javax.swing.JTextField();
        jBGauss = new javax.swing.JButton();
        jBCramer = new javax.swing.JButton();
        jBSetMatrix = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setResizable(false);

        jPMatrixPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTittle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittle.setText("Sistemas de ecuaciones");
        jPMatrixPanel.add(jLTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, -1));

        jLFILA.setText("Fila");
        jPMatrixPanel.add(jLFILA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPMatrixPanel.add(jTFilaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, -1));

        jLCOL.setText("Columna");
        jPMatrixPanel.add(jLCOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));
        jPMatrixPanel.add(jTColumnaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 30, -1));

        jBGauss.setText("GAUSS");
        jPMatrixPanel.add(jBGauss, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 90, -1));

        jBCramer.setText("CRAMER");
        jPMatrixPanel.add(jBCramer, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 90, -1));

        jBSetMatrix.setText("OK");
        jPMatrixPanel.add(jBSetMatrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMatrixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMatrixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcuacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcuacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcuacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcuacionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcuacionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCramer;
    private javax.swing.JButton jBGauss;
    private javax.swing.JButton jBSetMatrix;
    private javax.swing.JLabel jLCOL;
    private javax.swing.JLabel jLFILA;
    private javax.swing.JLabel jLTittle;
    private javax.swing.JPanel jPMatrixPanel;
    private javax.swing.JTextField jTColumnaA;
    private javax.swing.JTextField jTFilaA;
    // End of variables declaration//GEN-END:variables

}
