package View;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Javier
 */
public class MatrixCalcView extends javax.swing.JFrame {

    private javax.swing.JTextField jTmatrixA[][];
    private javax.swing.JTextField jTmatrixB[][];
    private javax.swing.JTextField jTmatrixResult[][];
    private final int WMATRIXBOX = 20;
    private final int HMATRIXBOX = -1;

    public MatrixCalcView() {
        initComponents();
        initJTmatrixComponents();
        setLocationRelativeTo(null);
           
    }

    public void initJTmatrixComponents() {
        initMatrixArray();
        posJTmatrixA();
        posJTmatrixB();
        posJTmatrixResult();
    }

    public void initMatrixArray() {
        jTmatrixA = new JTextField[5][5];
        jTmatrixB = new JTextField[5][5];
        jTmatrixResult = new JTextField[5][5];

        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                jTmatrixA[i][j] = new JTextField();
                jTmatrixB[i][j] = new JTextField();
                jTmatrixResult[i][j] = new JTextField();

            }
        }
    }

    public void posJTmatrixA() {
        int matrixAposX;
        int matrixAposY = 140;

        for (int i = 0; i < 5; i++) {
            matrixAposX = 30;
            for (int j = 0; j < 5; j++) {
                jPMatrixPanel.add(jTmatrixA[i][j], new org.netbeans.lib.awtextra.AbsoluteConstraints(matrixAposX, matrixAposY, WMATRIXBOX, HMATRIXBOX));
                matrixAposX += 30;
            }
            matrixAposY += 30;
        }
    }

    public void posJTmatrixB() {
        int matrixBposX;
        int matrixBposY = 140;

        for (int i = 0; i < 5; i++) {
            matrixBposX = 330;
            for (int j = 0; j < 5; j++) {
                jPMatrixPanel.add(jTmatrixB[i][j], new org.netbeans.lib.awtextra.AbsoluteConstraints(matrixBposX, matrixBposY, WMATRIXBOX, HMATRIXBOX));
                matrixBposX += 30;
            }
            matrixBposY += 30;
        }
    }

    public void posJTmatrixResult() {
        int matrixRposX;
        int matrixRposY = 320;
        for (int i = 0; i < 5; i++) {
            matrixRposX = 180;
            for (int j = 0; j < 5; j++) {
                jTmatrixResult[i][j].setEditable(false);
                jPMatrixPanel.add(jTmatrixResult[i][j], new org.netbeans.lib.awtextra.AbsoluteConstraints(matrixRposX, matrixRposY, WMATRIXBOX, HMATRIXBOX));
                matrixRposX += 30;
            }
            matrixRposY += 30;
        }
    }

    public void showMatrixResult(float[][] resultData) {
        for (int i = 0; i < resultData.length; i++) {
            for (int j = 0; j < resultData[i].length; j++) {
                jTmatrixResult[i][j].setText(String.valueOf(resultData[i][j]));
            }
        }
    }

    public JButton getjBAinverse() {
        return jBAinverse;
    }

    public JButton getjBAminusB() {
        return jBAminusB;
    }

    public JButton getjBAperB() {
        return jBAperB;
    }

    public JButton getjBAplusB() {
        return jBAplusB;
    }

    public JButton getjBBinverse() {
        return jBBinverse;
    }

    public JTextField getjTColumnaA() {
        return jTColumnaA;
    }

    public JTextField getjTColumnaB() {
        return jTColumnaB;
    }

    public JTextField getjTFilaA() {
        return jTFilaA;
    }

    public JTextField getjTFilaB() {
        return jTFilaB;
    }

    public JTextField[][] getjTmatrixA() {
        return jTmatrixA;
    }

    public JTextField[][] getjTmatrixB() {
        return jTmatrixB;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMatrixPanel = new javax.swing.JPanel();
        jLTittle = new javax.swing.JLabel();
        jBAplusB = new javax.swing.JButton();
        jBAminusB = new javax.swing.JButton();
        jBAperB = new javax.swing.JButton();
        jTFilaA = new javax.swing.JTextField();
        jTColumnaA = new javax.swing.JTextField();
        jTFilaB = new javax.swing.JTextField();
        jTColumnaB = new javax.swing.JTextField();
        jLFILA = new javax.swing.JLabel();
        jLCOL = new javax.swing.JLabel();
        jLFILAB = new javax.swing.JLabel();
        jLCOLB = new javax.swing.JLabel();
        jBAinverse = new javax.swing.JButton();
        jBBinverse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPMatrixPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTittle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittle.setText("Calculadora de matrices");
        jPMatrixPanel.add(jLTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 500, -1));

        jBAplusB.setText("A + B");
        jPMatrixPanel.add(jBAplusB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jBAminusB.setText("A - B");
        jPMatrixPanel.add(jBAminusB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, -1));

        jBAperB.setText("A * B");
        jPMatrixPanel.add(jBAperB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 60, -1));
        jPMatrixPanel.add(jTFilaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 30, -1));
        jPMatrixPanel.add(jTColumnaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 30, -1));
        jPMatrixPanel.add(jTFilaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 30, -1));
        jPMatrixPanel.add(jTColumnaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 30, -1));

        jLFILA.setText("FILA");
        jPMatrixPanel.add(jLFILA, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 80, -1, -1));

        jLCOL.setText("COLUMNA");
        jPMatrixPanel.add(jLCOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLFILAB.setText("FILA");
        jPMatrixPanel.add(jLFILAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 80, -1, -1));

        jLCOLB.setText("COLUMNA");
        jPMatrixPanel.add(jLCOLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jBAinverse.setText("A-");
        jPMatrixPanel.add(jBAinverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jBBinverse.setText("B-");
        jPMatrixPanel.add(jBBinverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMatrixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMatrixPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixCalcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixCalcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixCalcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixCalcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixCalcView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAinverse;
    private javax.swing.JButton jBAminusB;
    private javax.swing.JButton jBAperB;
    private javax.swing.JButton jBAplusB;
    private javax.swing.JButton jBBinverse;
    private javax.swing.JLabel jLCOL;
    private javax.swing.JLabel jLCOLB;
    private javax.swing.JLabel jLFILA;
    private javax.swing.JLabel jLFILAB;
    private javax.swing.JLabel jLTittle;
    private javax.swing.JPanel jPMatrixPanel;
    private javax.swing.JTextField jTColumnaA;
    private javax.swing.JTextField jTColumnaB;
    private javax.swing.JTextField jTFilaA;
    private javax.swing.JTextField jTFilaB;
    // End of variables declaration//GEN-END:variables
}
